build_project1/build_project1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from buildapp import views 

urlpatterns = [
	url(r'^$',views.index,name='index'),
	path('admin/', admin.site.urls),
	url(r'^buildapp/',include('buildapp.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/^$',views.special,name='special'),


]
  

build_project1/buildapp/urls.py
from django.conf.urls import url
from buildapp import views

# template urls
app_name = 'buildapp'

# Create urls here.

urlpatterns = [
	url(r'^register/$', views.register,name='register'),
	url(r'^user_login/$',views.user_login,name='user_login'),

]

build_project1/buildapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):


	user = models.OneToOneField(User,on_delete=models.CASCADE)# this adds more attributes with this code

	# additional 
	portfolio_site = models.URLField(blank=True)

	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


	def __str__(self):
		return self.user.username

build_project1/buildapp/forms.py
from django import forms
from django.contrib.auth.models import User
from buildapp.models import UserProfileInfo

# this creates the email and password fields for register form
class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	# this is what is being asked to be returned in the registration page
	class Meta():
		model = User
		fields = ('username', 'email','password')

	# this to is being returned to the registration page
class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site', 'profile_pic')

build_project1/buildapp/views.py
from django.shortcuts import render
from buildapp.forms import UserForm,UserProfileInfoForm


# django login imports
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required 



# Create your views here.
def index(request):
	return render(request, 'buildapp/index.html')


def register(request):

	# this will see if someone is registered or not
	registered = False 


	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)


		# check to see if the forms are valid

		if user_form.is_valid() and profile_form.is_valid():

			# Grab the user form save it and hash the password typed in by the user 
			user = user_form.save()
			user.set_password(user.password)# this is what hashes the password
			user.save() 

			# profile form check 
			profile= profile_form.save(commit=False)
			# sets up one to one relationship
			profile.user = user

			# this connects to the models profile_pic variable
			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()

			# if everything is true then do this
			registered = True
		else:
			print(user_form.errors,profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()

	return render(request,'buildapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})
 

# login section. 

def user_login(request):

	# this checks if the user is logged on 
	if request.method == 'POST':
		username = request.POST.get('username')#username and password are being pulled from login html
		password = request.POST.get('password')
		


		#django authentication which checks if the user who just typed in this data is authenticated
		user = authenticate(username=username,password=password)

		# if logged user will be redirected to the home page
		if user:
			if user.is_active:
				login(request,user)#this logins the user
				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse("ACCOUNT NOT ACTIVE")

		else:
			print('Someone tired to login and failed!')
			print('Username: {} and password {}'.format(username,password))
			return	HttpResponse('invalid login details supplied!')

	else:
		return render(request,'buildapp/login.html',{})

	


@login_required
def special(request):
	return HttpResponse("You are logged in Nice!")


#this means that someone has to be logged in 
@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

build_project1/templates/buildapp/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{%url 'index'%}">Home Page</a></li>
				<li><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
				<li><a class="navbar-link" href="{%url 'buildapp:register'%}">Register</a></li>

				{% if user.is_authenticated %}
					<li><a class="navbar-link" href="{%url 'logout'%}">Logout</a></li>

				{% else %}
					<li><a class="navbar-link" href="{%url 'buildapp:user_login'%}">Login</a></li>
				{% endif %}	

			</ul>
		</div>
	</nav>

	 <div>
		{% block body_block %}
		{% endblock %}	
	</div>

</body>
</html>

<!-- everything inside of the body of this file will be displayed on all the webpages. -->

build_project1/templates/buildapp/index.html
{% extends 'buildapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
	<h1>This Is The Intro</h1>
</div>

{% endblock %}

build_project1/templates/buildapp/login.html
{% extends 'buildapp/base.html' %}<!--The build app texts needs to be in quotes-->
{% block body_block %}

<div class="jumbotron">
	<h1>Please Login</h1>
	<form action="{% url 'buildapp:user_login' %}" method="post">
		{% csrf_token %} <!--whenever using a form this is needed-->
		<label for="username">Username:</label>
		<input type="text" name="username" placeholder="Enter Username">

		<label for="password">Password:</label>
		<input type="password" name="password">

		<input type="submit" name="" value="Login">
	</form>
</div>









{% endblock %}

build_project1/templates/buildapp/registration.html
{% extends 'buildapp/base.html' %}
{% load static %}


{% block body_block %}

<div class="jumbotron">
	{% if registered %}
		<h1>Thank you for registering!</h1>
	{% else %}
		<h1>Register Here!</h1>
		<h3>Fill out the form:</h3>	


		<form  enctype="multipart/form-data" method="post"><!--multipart needed form to work-->
			{% csrf_token %}
			{{ user_form.as_p }}
			{{ profile_form.as_p }}
			<input type="submit" name="" value="Register">
		</form>










	{% endif %}
</div>


{% endblock %}